/*
 * Suomen kuntien numerot ja nimet: Tilastokeskuksen luokituspalvelusta
 * (kunta_1_20250101, data.stat.fi) haettu ja vahvistettu suoraan API:sta.
 * Maakunta on päätelty kuntanumeroista tunnetun maakuntajaon perusteella —
 * tarkista poikkeustapaukset tarvittaessa erikseen.
 */

export type Municipality = {
  code: string
  name: string
  region: string
}

export const MUNICIPALITIES: Record<string, Municipality> = {
  "005": { code: "005", name: "Alajärvi", region: "Etelä-Pohjanmaa" },
  "009": { code: "009", name: "Alavieska", region: "Pohjois-Pohjanmaa" },
  "010": { code: "010", name: "Alavus", region: "Etelä-Pohjanmaa" },
  "016": { code: "016", name: "Asikkala", region: "Päijät-Häme" },
  "018": { code: "018", name: "Askola", region: "Uusimaa" },
  "019": { code: "019", name: "Aura", region: "Varsinais-Suomi" },
  "020": { code: "020", name: "Akaa", region: "Pirkanmaa" },
  "035": { code: "035", name: "Brändö", region: "Ahvenanmaa" },
  "043": { code: "043", name: "Eckerö", region: "Ahvenanmaa" },
  "046": { code: "046", name: "Enonkoski", region: "Etelä-Savo" },
  "047": { code: "047", name: "Enontekiö", region: "Lappi" },
  "049": { code: "049", name: "Espoo", region: "Uusimaa" },
  "050": { code: "050", name: "Eura", region: "Satakunta" },
  "051": { code: "051", name: "Eurajoki", region: "Satakunta" },
  "052": { code: "052", name: "Evijärvi", region: "Etelä-Pohjanmaa" },
  "060": { code: "060", name: "Finström", region: "Ahvenanmaa" },
  "061": { code: "061", name: "Forssa", region: "Kanta-Häme" },
  "062": { code: "062", name: "Föglö", region: "Ahvenanmaa" },
  "065": { code: "065", name: "Geta", region: "Ahvenanmaa" },
  "069": { code: "069", name: "Haapajärvi", region: "Pohjois-Pohjanmaa" },
  "071": { code: "071", name: "Haapavesi", region: "Pohjois-Pohjanmaa" },
  "072": { code: "072", name: "Hailuoto", region: "Pohjois-Pohjanmaa" },
  "074": { code: "074", name: "Halsua", region: "Keski-Pohjanmaa" },
  "075": { code: "075", name: "Hamina", region: "Kymenlaakso" },
  "076": { code: "076", name: "Hammarland", region: "Ahvenanmaa" },
  "077": { code: "077", name: "Hankasalmi", region: "Keski-Suomi" },
  "078": { code: "078", name: "Hanko", region: "Uusimaa" },
  "079": { code: "079", name: "Harjavalta", region: "Satakunta" },
  "081": { code: "081", name: "Hartola", region: "Päijät-Häme" },
  "082": { code: "082", name: "Hattula", region: "Kanta-Häme" },
  "086": { code: "086", name: "Hausjärvi", region: "Kanta-Häme" },
  "090": { code: "090", name: "Heinävesi", region: "Etelä-Savo" },
  "091": { code: "091", name: "Helsinki", region: "Uusimaa" },
  "092": { code: "092", name: "Vantaa", region: "Uusimaa" },
  "097": { code: "097", name: "Hirvensalmi", region: "Etelä-Savo" },
  "098": { code: "098", name: "Hollola", region: "Päijät-Häme" },
  "102": { code: "102", name: "Huittinen", region: "Satakunta" },
  "103": { code: "103", name: "Humppila", region: "Kanta-Häme" },
  "105": { code: "105", name: "Hyrynsalmi", region: "Kainuu" },
  "106": { code: "106", name: "Hyvinkää", region: "Uusimaa" },
  "108": { code: "108", name: "Hämeenkyrö", region: "Pirkanmaa" },
  "109": { code: "109", name: "Hämeenlinna", region: "Kanta-Häme" },
  "111": { code: "111", name: "Heinola", region: "Päijät-Häme" },
  "139": { code: "139", name: "Ii", region: "Pohjois-Pohjanmaa" },
  "140": { code: "140", name: "Iisalmi", region: "Pohjois-Savo" },
  "142": { code: "142", name: "Iitti", region: "Kymenlaakso" },
  "143": { code: "143", name: "Ikaalinen", region: "Pirkanmaa" },
  "145": { code: "145", name: "Ilmajoki", region: "Etelä-Pohjanmaa" },
  "146": { code: "146", name: "Ilomantsi", region: "Pohjois-Karjala" },
  "148": { code: "148", name: "Inari", region: "Lappi" },
  "149": { code: "149", name: "Inkoo", region: "Uusimaa" },
  "151": { code: "151", name: "Isojoki", region: "Etelä-Pohjanmaa" },
  "152": { code: "152", name: "Isokyrö", region: "Etelä-Pohjanmaa" },
  "153": { code: "153", name: "Imatra", region: "Etelä-Karjala" },
  "165": { code: "165", name: "Janakkala", region: "Kanta-Häme" },
  "167": { code: "167", name: "Joensuu", region: "Pohjois-Karjala" },
  "169": { code: "169", name: "Jokioinen", region: "Kanta-Häme" },
  "170": { code: "170", name: "Jomala", region: "Ahvenanmaa" },
  "171": { code: "171", name: "Joroinen", region: "Etelä-Savo" },
  "172": { code: "172", name: "Joutsa", region: "Keski-Suomi" },
  "176": { code: "176", name: "Juuka", region: "Pohjois-Karjala" },
  "177": { code: "177", name: "Juupajoki", region: "Pirkanmaa" },
  "178": { code: "178", name: "Juva", region: "Etelä-Savo" },
  "179": { code: "179", name: "Jyväskylä", region: "Keski-Suomi" },
  "181": { code: "181", name: "Jämijärvi", region: "Satakunta" },
  "182": { code: "182", name: "Jämsä", region: "Keski-Suomi" },
  "186": { code: "186", name: "Järvenpää", region: "Uusimaa" },
  "202": { code: "202", name: "Kaarina", region: "Varsinais-Suomi" },
  "204": { code: "204", name: "Kaavi", region: "Pohjois-Savo" },
  "205": { code: "205", name: "Kajaani", region: "Kainuu" },
  "208": { code: "208", name: "Kalajoki", region: "Pohjois-Pohjanmaa" },
  "211": { code: "211", name: "Kangasala", region: "Pirkanmaa" },
  "213": { code: "213", name: "Kangasniemi", region: "Etelä-Savo" },
  "214": { code: "214", name: "Kankaanpää", region: "Satakunta" },
  "216": { code: "216", name: "Kannonkoski", region: "Keski-Suomi" },
  "217": { code: "217", name: "Kannus", region: "Keski-Pohjanmaa" },
  "218": { code: "218", name: "Karijoki", region: "Etelä-Pohjanmaa" },
  "224": { code: "224", name: "Karkkila", region: "Uusimaa" },
  "226": { code: "226", name: "Karstula", region: "Keski-Suomi" },
  "230": { code: "230", name: "Karvia", region: "Satakunta" },
  "231": { code: "231", name: "Kaskinen", region: "Pohjanmaa" },
  "232": { code: "232", name: "Kauhajoki", region: "Etelä-Pohjanmaa" },
  "233": { code: "233", name: "Kauhava", region: "Etelä-Pohjanmaa" },
  "235": { code: "235", name: "Kauniainen", region: "Uusimaa" },
  "236": { code: "236", name: "Kaustinen", region: "Keski-Pohjanmaa" },
  "239": { code: "239", name: "Keitele", region: "Pohjois-Savo" },
  "240": { code: "240", name: "Kemi", region: "Lappi" },
  "241": { code: "241", name: "Keminmaa", region: "Lappi" },
  "244": { code: "244", name: "Kempele", region: "Pohjois-Pohjanmaa" },
  "245": { code: "245", name: "Kerava", region: "Uusimaa" },
  "249": { code: "249", name: "Keuruu", region: "Keski-Suomi" },
  "250": { code: "250", name: "Kihniö", region: "Pirkanmaa" },
  "256": { code: "256", name: "Kinnula", region: "Keski-Suomi" },
  "257": { code: "257", name: "Kirkkonummi", region: "Uusimaa" },
  "260": { code: "260", name: "Kitee", region: "Pohjois-Karjala" },
  "261": { code: "261", name: "Kittilä", region: "Lappi" },
  "263": { code: "263", name: "Kiuruvesi", region: "Pohjois-Savo" },
  "265": { code: "265", name: "Kivijärvi", region: "Keski-Suomi" },
  "271": { code: "271", name: "Kokemäki", region: "Satakunta" },
  "272": { code: "272", name: "Kokkola", region: "Keski-Pohjanmaa" },
  "273": { code: "273", name: "Kolari", region: "Lappi" },
  "275": { code: "275", name: "Konnevesi", region: "Keski-Suomi" },
  "276": { code: "276", name: "Kontiolahti", region: "Pohjois-Karjala" },
  "280": { code: "280", name: "Korsnäs", region: "Pohjanmaa" },
  "284": { code: "284", name: "Koski Tl", region: "Varsinais-Suomi" },
  "285": { code: "285", name: "Kotka", region: "Kymenlaakso" },
  "286": { code: "286", name: "Kouvola", region: "Kymenlaakso" },
  "287": { code: "287", name: "Kristiinankaupunki", region: "Pohjanmaa" },
  "288": { code: "288", name: "Kruunupyy", region: "Pohjanmaa" },
  "290": { code: "290", name: "Kuhmo", region: "Kainuu" },
  "291": { code: "291", name: "Kuhmoinen", region: "Keski-Suomi" },
  "295": { code: "295", name: "Kumlinge", region: "Ahvenanmaa" },
  "297": { code: "297", name: "Kuopio", region: "Pohjois-Savo" },
  "300": { code: "300", name: "Kuortane", region: "Etelä-Pohjanmaa" },
  "301": { code: "301", name: "Kurikka", region: "Etelä-Pohjanmaa" },
  "304": { code: "304", name: "Kustavi", region: "Varsinais-Suomi" },
  "305": { code: "305", name: "Kuusamo", region: "Pohjois-Pohjanmaa" },
  "309": { code: "309", name: "Outokumpu", region: "Pohjois-Karjala" },
  "312": { code: "312", name: "Kyyjärvi", region: "Keski-Suomi" },
  "316": { code: "316", name: "Kärkölä", region: "Päijät-Häme" },
  "317": { code: "317", name: "Kärsämäki", region: "Pohjois-Pohjanmaa" },
  "318": { code: "318", name: "Kökar", region: "Ahvenanmaa" },
  "320": { code: "320", name: "Kemijärvi", region: "Lappi" },
  "322": { code: "322", name: "Kemiönsaari", region: "Varsinais-Suomi" },
  "398": { code: "398", name: "Lahti", region: "Päijät-Häme" },
  "399": { code: "399", name: "Laihia", region: "Etelä-Pohjanmaa" },
  "400": { code: "400", name: "Laitila", region: "Varsinais-Suomi" },
  "402": { code: "402", name: "Lapinlahti", region: "Pohjois-Savo" },
  "403": { code: "403", name: "Lappajärvi", region: "Etelä-Pohjanmaa" },
  "405": { code: "405", name: "Lappeenranta", region: "Etelä-Karjala" },
  "407": { code: "407", name: "Lapinjärvi", region: "Uusimaa" },
  "408": { code: "408", name: "Lapua", region: "Etelä-Pohjanmaa" },
  "410": { code: "410", name: "Laukaa", region: "Keski-Suomi" },
  "416": { code: "416", name: "Lemi", region: "Etelä-Karjala" },
  "417": { code: "417", name: "Lemland", region: "Ahvenanmaa" },
  "418": { code: "418", name: "Lempäälä", region: "Pirkanmaa" },
  "420": { code: "420", name: "Leppävirta", region: "Pohjois-Savo" },
  "421": { code: "421", name: "Lestijärvi", region: "Keski-Pohjanmaa" },
  "422": { code: "422", name: "Lieksa", region: "Pohjois-Karjala" },
  "423": { code: "423", name: "Lieto", region: "Varsinais-Suomi" },
  "425": { code: "425", name: "Liminka", region: "Pohjois-Pohjanmaa" },
  "426": { code: "426", name: "Liperi", region: "Pohjois-Karjala" },
  "430": { code: "430", name: "Loimaa", region: "Varsinais-Suomi" },
  "433": { code: "433", name: "Loppi", region: "Kanta-Häme" },
  "434": { code: "434", name: "Loviisa", region: "Uusimaa" },
  "435": { code: "435", name: "Luhanka", region: "Keski-Suomi" },
  "436": { code: "436", name: "Lumijoki", region: "Pohjois-Pohjanmaa" },
  "438": { code: "438", name: "Lumparland", region: "Ahvenanmaa" },
  "440": { code: "440", name: "Luoto", region: "Pohjanmaa" },
  "441": { code: "441", name: "Luumäki", region: "Etelä-Karjala" },
  "444": { code: "444", name: "Lohja", region: "Uusimaa" },
  "445": { code: "445", name: "Parainen", region: "Varsinais-Suomi" },
  "475": { code: "475", name: "Maalahti", region: "Pohjanmaa" },
  "478": { code: "478", name: "Maarianhamina - Mariehamn", region: "Ahvenanmaa" },
  "480": { code: "480", name: "Marttila", region: "Varsinais-Suomi" },
  "481": { code: "481", name: "Masku", region: "Varsinais-Suomi" },
  "483": { code: "483", name: "Merijärvi", region: "Pohjois-Pohjanmaa" },
  "484": { code: "484", name: "Merikarvia", region: "Satakunta" },
  "489": { code: "489", name: "Miehikkälä", region: "Kymenlaakso" },
  "491": { code: "491", name: "Mikkeli", region: "Etelä-Savo" },
  "494": { code: "494", name: "Muhos", region: "Pohjois-Pohjanmaa" },
  "495": { code: "495", name: "Multia", region: "Keski-Suomi" },
  "498": { code: "498", name: "Muonio", region: "Lappi" },
  "499": { code: "499", name: "Mustasaari", region: "Pohjanmaa" },
  "500": { code: "500", name: "Muurame", region: "Keski-Suomi" },
  "503": { code: "503", name: "Mynämäki", region: "Varsinais-Suomi" },
  "504": { code: "504", name: "Myrskylä", region: "Uusimaa" },
  "505": { code: "505", name: "Mäntsälä", region: "Uusimaa" },
  "507": { code: "507", name: "Mäntyharju", region: "Etelä-Savo" },
  "508": { code: "508", name: "Mänttä-Vilppula", region: "Pirkanmaa" },
  "529": { code: "529", name: "Naantali", region: "Varsinais-Suomi" },
  "531": { code: "531", name: "Nakkila", region: "Satakunta" },
  "535": { code: "535", name: "Nivala", region: "Pohjois-Pohjanmaa" },
  "536": { code: "536", name: "Nokia", region: "Pirkanmaa" },
  "538": { code: "538", name: "Nousiainen", region: "Varsinais-Suomi" },
  "541": { code: "541", name: "Nurmes", region: "Pohjois-Karjala" },
  "543": { code: "543", name: "Nurmijärvi", region: "Uusimaa" },
  "545": { code: "545", name: "Närpiö", region: "Pohjanmaa" },
  "560": { code: "560", name: "Orimattila", region: "Päijät-Häme" },
  "561": { code: "561", name: "Oripää", region: "Varsinais-Suomi" },
  "562": { code: "562", name: "Orivesi", region: "Pirkanmaa" },
  "563": { code: "563", name: "Oulainen", region: "Pohjois-Pohjanmaa" },
  "564": { code: "564", name: "Oulu", region: "Pohjois-Pohjanmaa" },
  "576": { code: "576", name: "Padasjoki", region: "Päijät-Häme" },
  "577": { code: "577", name: "Paimio", region: "Varsinais-Suomi" },
  "578": { code: "578", name: "Paltamo", region: "Kainuu" },
  "580": { code: "580", name: "Parikkala", region: "Etelä-Karjala" },
  "581": { code: "581", name: "Parkano", region: "Pirkanmaa" },
  "583": { code: "583", name: "Pelkosenniemi", region: "Lappi" },
  "584": { code: "584", name: "Perho", region: "Keski-Pohjanmaa" },
  "592": { code: "592", name: "Petäjävesi", region: "Keski-Suomi" },
  "593": { code: "593", name: "Pieksämäki", region: "Etelä-Savo" },
  "595": { code: "595", name: "Pielavesi", region: "Pohjois-Savo" },
  "598": { code: "598", name: "Pietarsaari", region: "Pohjanmaa" },
  "599": { code: "599", name: "Pedersören kunta", region: "Pohjanmaa" },
  "601": { code: "601", name: "Pihtipudas", region: "Keski-Suomi" },
  "604": { code: "604", name: "Pirkkala", region: "Pirkanmaa" },
  "607": { code: "607", name: "Polvijärvi", region: "Pohjois-Karjala" },
  "608": { code: "608", name: "Pomarkku", region: "Satakunta" },
  "609": { code: "609", name: "Pori", region: "Satakunta" },
  "611": { code: "611", name: "Pornainen", region: "Uusimaa" },
  "614": { code: "614", name: "Posio", region: "Lappi" },
  "615": { code: "615", name: "Pudasjärvi", region: "Pohjois-Pohjanmaa" },
  "616": { code: "616", name: "Pukkila", region: "Uusimaa" },
  "619": { code: "619", name: "Punkalaidun", region: "Pirkanmaa" },
  "620": { code: "620", name: "Puolanka", region: "Kainuu" },
  "623": { code: "623", name: "Puumala", region: "Etelä-Savo" },
  "624": { code: "624", name: "Pyhtää", region: "Kymenlaakso" },
  "625": { code: "625", name: "Pyhäjoki", region: "Pohjois-Pohjanmaa" },
  "626": { code: "626", name: "Pyhäjärvi", region: "Pohjois-Pohjanmaa" },
  "630": { code: "630", name: "Pyhäntä", region: "Pohjois-Pohjanmaa" },
  "631": { code: "631", name: "Pyhäranta", region: "Varsinais-Suomi" },
  "635": { code: "635", name: "Pälkäne", region: "Pirkanmaa" },
  "636": { code: "636", name: "Pöytyä", region: "Varsinais-Suomi" },
  "638": { code: "638", name: "Porvoo", region: "Uusimaa" },
  "678": { code: "678", name: "Raahe", region: "Pohjois-Pohjanmaa" },
  "680": { code: "680", name: "Raisio", region: "Varsinais-Suomi" },
  "681": { code: "681", name: "Rantasalmi", region: "Etelä-Savo" },
  "683": { code: "683", name: "Ranua", region: "Lappi" },
  "684": { code: "684", name: "Rauma", region: "Satakunta" },
  "686": { code: "686", name: "Rautalampi", region: "Pohjois-Savo" },
  "687": { code: "687", name: "Rautavaara", region: "Pohjois-Savo" },
  "689": { code: "689", name: "Rautjärvi", region: "Etelä-Karjala" },
  "691": { code: "691", name: "Reisjärvi", region: "Pohjois-Pohjanmaa" },
  "694": { code: "694", name: "Riihimäki", region: "Kanta-Häme" },
  "697": { code: "697", name: "Ristijärvi", region: "Kainuu" },
  "698": { code: "698", name: "Rovaniemi", region: "Lappi" },
  "700": { code: "700", name: "Ruokolahti", region: "Etelä-Karjala" },
  "702": { code: "702", name: "Ruovesi", region: "Pirkanmaa" },
  "704": { code: "704", name: "Rusko", region: "Varsinais-Suomi" },
  "707": { code: "707", name: "Rääkkylä", region: "Pohjois-Karjala" },
  "710": { code: "710", name: "Raasepori", region: "Uusimaa" },
  "729": { code: "729", name: "Saarijärvi", region: "Keski-Suomi" },
  "732": { code: "732", name: "Salla", region: "Lappi" },
  "734": { code: "734", name: "Salo", region: "Varsinais-Suomi" },
  "736": { code: "736", name: "Saltvik", region: "Ahvenanmaa" },
  "738": { code: "738", name: "Sauvo", region: "Varsinais-Suomi" },
  "739": { code: "739", name: "Savitaipale", region: "Etelä-Karjala" },
  "740": { code: "740", name: "Savonlinna", region: "Etelä-Savo" },
  "742": { code: "742", name: "Savukoski", region: "Lappi" },
  "743": { code: "743", name: "Seinäjoki", region: "Etelä-Pohjanmaa" },
  "746": { code: "746", name: "Sievi", region: "Pohjois-Pohjanmaa" },
  "747": { code: "747", name: "Siikainen", region: "Satakunta" },
  "748": { code: "748", name: "Siikajoki", region: "Pohjois-Pohjanmaa" },
  "749": { code: "749", name: "Siilinjärvi", region: "Pohjois-Savo" },
  "751": { code: "751", name: "Simo", region: "Lappi" },
  "753": { code: "753", name: "Sipoo", region: "Uusimaa" },
  "755": { code: "755", name: "Siuntio", region: "Uusimaa" },
  "758": { code: "758", name: "Sodankylä", region: "Lappi" },
  "759": { code: "759", name: "Soini", region: "Etelä-Pohjanmaa" },
  "761": { code: "761", name: "Somero", region: "Varsinais-Suomi" },
  "762": { code: "762", name: "Sonkajärvi", region: "Pohjois-Savo" },
  "765": { code: "765", name: "Sotkamo", region: "Kainuu" },
  "766": { code: "766", name: "Sottunga", region: "Ahvenanmaa" },
  "768": { code: "768", name: "Sulkava", region: "Etelä-Savo" },
  "771": { code: "771", name: "Sund", region: "Ahvenanmaa" },
  "777": { code: "777", name: "Suomussalmi", region: "Kainuu" },
  "778": { code: "778", name: "Suonenjoki", region: "Pohjois-Savo" },
  "781": { code: "781", name: "Sysmä", region: "Päijät-Häme" },
  "783": { code: "783", name: "Säkylä", region: "Satakunta" },
  "785": { code: "785", name: "Vaala", region: "Pohjois-Pohjanmaa" },
  "790": { code: "790", name: "Sastamala", region: "Pirkanmaa" },
  "791": { code: "791", name: "Siikalatva", region: "Pohjois-Pohjanmaa" },
  "831": { code: "831", name: "Taipalsaari", region: "Etelä-Karjala" },
  "832": { code: "832", name: "Taivalkoski", region: "Pohjois-Pohjanmaa" },
  "833": { code: "833", name: "Taivassalo", region: "Varsinais-Suomi" },
  "834": { code: "834", name: "Tammela", region: "Kanta-Häme" },
  "837": { code: "837", name: "Tampere", region: "Pirkanmaa" },
  "844": { code: "844", name: "Tervo", region: "Pohjois-Savo" },
  "845": { code: "845", name: "Tervola", region: "Lappi" },
  "846": { code: "846", name: "Teuva", region: "Etelä-Pohjanmaa" },
  "848": { code: "848", name: "Tohmajärvi", region: "Pohjois-Karjala" },
  "849": { code: "849", name: "Toholampi", region: "Keski-Pohjanmaa" },
  "850": { code: "850", name: "Toivakka", region: "Keski-Suomi" },
  "851": { code: "851", name: "Tornio", region: "Lappi" },
  "853": { code: "853", name: "Turku", region: "Varsinais-Suomi" },
  "854": { code: "854", name: "Pello", region: "Lappi" },
  "857": { code: "857", name: "Tuusniemi", region: "Pohjois-Savo" },
  "858": { code: "858", name: "Tuusula", region: "Uusimaa" },
  "859": { code: "859", name: "Tyrnävä", region: "Pohjois-Pohjanmaa" },
  "886": { code: "886", name: "Ulvila", region: "Satakunta" },
  "887": { code: "887", name: "Urjala", region: "Pirkanmaa" },
  "889": { code: "889", name: "Utajärvi", region: "Pohjois-Pohjanmaa" },
  "890": { code: "890", name: "Utsjoki", region: "Lappi" },
  "892": { code: "892", name: "Uurainen", region: "Keski-Suomi" },
  "893": { code: "893", name: "Uusikaarlepyy", region: "Pohjanmaa" },
  "895": { code: "895", name: "Uusikaupunki", region: "Varsinais-Suomi" },
  "905": { code: "905", name: "Vaasa", region: "Pohjanmaa" },
  "908": { code: "908", name: "Valkeakoski", region: "Pirkanmaa" },
  "915": { code: "915", name: "Varkaus", region: "Pohjois-Savo" },
  "918": { code: "918", name: "Vehmaa", region: "Varsinais-Suomi" },
  "921": { code: "921", name: "Vesanto", region: "Pohjois-Savo" },
  "922": { code: "922", name: "Vesilahti", region: "Pirkanmaa" },
  "924": { code: "924", name: "Veteli", region: "Keski-Pohjanmaa" },
  "925": { code: "925", name: "Vieremä", region: "Pohjois-Savo" },
  "927": { code: "927", name: "Vihti", region: "Uusimaa" },
  "931": { code: "931", name: "Viitasaari", region: "Keski-Suomi" },
  "934": { code: "934", name: "Vimpeli", region: "Etelä-Pohjanmaa" },
  "935": { code: "935", name: "Virolahti", region: "Kymenlaakso" },
  "936": { code: "936", name: "Virrat", region: "Pirkanmaa" },
  "941": { code: "941", name: "Vårdö", region: "Ahvenanmaa" },
  "946": { code: "946", name: "Vöyri", region: "Pohjanmaa" },
  "976": { code: "976", name: "Ylitornio", region: "Lappi" },
  "977": { code: "977", name: "Ylivieska", region: "Pohjois-Pohjanmaa" },
  "980": { code: "980", name: "Ylöjärvi", region: "Pirkanmaa" },
  "981": { code: "981", name: "Ypäjä", region: "Kanta-Häme" },
  "989": { code: "989", name: "Ähtäri", region: "Etelä-Pohjanmaa" },
  "992": { code: "992", name: "Äänekoski", region: "Keski-Suomi" },
}

export function getMunicipality(code: string | null | undefined): Municipality | null {
  if (!code) return null
  return MUNICIPALITIES[code.padStart(3, "0")] ?? null
}

const MUNICIPALITIES_BY_NAME: Record<string, Municipality> = Object.values(
  MUNICIPALITIES
).reduce(
  (acc, m) => {
    acc[m.name.toLowerCase()] = m
    return acc
  },
  {} as Record<string, Municipality>
)

export function getMunicipalityByName(
  name: string | null | undefined
): Municipality | null {
  if (!name) return null
  return MUNICIPALITIES_BY_NAME[name.trim().toLowerCase()] ?? null
}
