import { fetchSttPressroomProjects } from "./sttPressroom"

export async function fetchEspoonAsunnotSource() {
  return fetchSttPressroomProjects({
    publisherId: "69820862",
    sourceName: "espoon_asunnot",
    referer: "https://www.sttinfo.fi/uutishuone/69820862/espoon-asunnot-oy",
    projectKeywords: [
      "rakentaa",
      "rakentaminen",
      "rakentuu",
      "toteuttaa",
      "hanke",
      "kohde",
      "asunto",
      "asuntoa",
      "asunnot",
      "vuokra-asunto",
      "vuokra-asunnot",
      "kerrostalo",
      "kortteli",
      "uudiskohde",
      "uudisrakennus",
      "peruskorjaus",
      "peruskorjauksen",
      "korjaus",
    ],
    excludeKeywords: [
      "nimity",
      "osavuosikatsaus",
      "tilinpäätös",
      "markkina",
      "tulos",
      "vastuullisuus",
      "johtaja",
      "strategia",
      "vuosikertomus",
      "vuokrat nousevat",
      "käyttää",
      "miljoonaa euroa",
    ],
    completedKeywords: [
      "valmistui",
      "valmistunut",
      "luovutettu",
      "otettu käyttöön",
      "vastaanotettu",
      "on valmis",
    ],
  })
}
