import { fetchSttPressroomProjects } from "./sttPressroom"

export async function fetchJatkeSource() {
  return fetchSttPressroomProjects({
    publisherId: "69820730",
    sourceName: "jatke",
    referer: "https://www.sttinfo.fi/uutishuone/69820730/jatke",
    projectKeywords: [
      "rakentaa",
      "rakentaminen",
      "rakentuu",
      "toteuttaa",
      "urakka",
      "hanke",
      "kohde",
      "asunto",
      "asuntoa",
      "asunnot",
      "kerrostalo",
      "kortteli",
      "toimitila",
      "toimitilat",
      "koulu",
      "päiväkoti",
      "sairaala",
      "hoivakoti",
      "palvelutalo",
      "uudiskohde",
      "peruskorjaus",
    ],
    excludeKeywords: [
      "nimity",
      "osavuosikatsaus",
      "tilinpäätös",
      "markkina",
      "tulos",
      "vastuullisuus",
      "johtaja",
      "yhtiökokous",
      "strategia",
    ],
    completedKeywords: [
      "valmistui",
      "valmistunut",
      "luovutettu",
      "otettu käyttöön",
      "vastaanotettu",
      "on valmis",
    ],
  })
}
