import { fetchSttPressroomProjects } from "./sttPressroom"

export async function fetchMeijouSource() {
  return fetchSttPressroomProjects({
    publisherId: "69821233",
    sourceName: "meijou",
    referer: "https://www.sttinfo.fi/uutishuone/69821233/meijou-oy",
    projectKeywords: [
      "rakentaa",
      "rakentaminen",
      "rakentuu",
      "toteuttaa",
      "urakka",
      "urakointi",
      "urakoinnin",
      "aloittaa",
      "käynnistyy",
      "käynnistää",
      "hanke",
      "kohde",
      "toimitila",
      "toimitilat",
      "liikekiinteistö",
      "logistiikka",
      "varasto",
      "tuotantotila",
      "teollisuus",
      "liiketila",
      "keskus",
      "myymälä",
      "peruskorjaus",
      "laajennus",
      "energialuokka",
    ],
    excludeKeywords: [
      "nimity",
      "osavuosikatsaus",
      "tilinpäätös",
      "markkina",
      "tulos",
      "vastuullisuus",
      "johtaja",
      "yhtiökokous",
      "strategia",
      "vuosikertomus",
      "teki historiaa",
    ],
    completedKeywords: [
      "valmistui",
      "valmistunut",
      "luovutettu",
      "otettu käyttöön",
      "vastaanotettu",
      "on valmis",
    ],
  })
}
